[package]
name = "quickserve"
version = "0.1.0"
authors = ["Jonathan Balls <j.balls@btopenworld.com>"]

[dependencies]
thrussh = "0.9.1"
futures = "0.1"
tokio-core = "0.1"
env_logger = "0.4.0"
iron = "0.5.1"
rustc-serialize = "0.3"
mount = "0.3"
staticfile = "*"
router = "0.5"

